const data = [
    {
      id: 1,
      title: "iPhone 9",
      description: "An apple mobile which is nothing like apple",
      price: 549,
      discountPercentage: 12.96,
      rating: 4.69,
      stock: 94,
      brand: "Apple",
      category: "smartphones",
      thumbnail: "https://i.pinimg.com/originals/6b/3f/6b/6b3f6b9bb5ff4746d4876f301c8d00bd.jpg",
      images: [
        "https://i.pinimg.com/originals/6b/3f/6b/6b3f6b9bb5ff4746d4876f301c8d00bd.jpg",
        "https://i.ytimg.com/vi/Z4faIxHsBgc/maxresdefault.jpg",
        "https://i.ytimg.com/vi/2Q0Pf_Edlq4/maxresdefault.jpg",
        "https://i.ytimg.com/vi/PtWy_wfhDcs/maxresdefault.jpg",
        "https://tse3.mm.bing.net/th?id=OIP.u6YkbUU7snW0pzZTeTJ5UwHaF5&pid=Api&P=0&h=180",
      ],
    },
    {
      id: 2,
      title: "iPhone X",
      description:
        "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
      price: 899,
      discountPercentage: 17.94,
      rating: 4.44,
      stock: 34,
      brand: "Apple",
      category: "smartphones",
      thumbnail: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5789/5789725cv11d.jpg",
      images: [
        "https://freepngimg.com/thumb/apple_iphone/2-2-apple-iphone-picture.png",
        "https://tse2.mm.bing.net/th?id=OIP.2roy-5BZyBYVI55J2eXH4gHaH9&pid=Api&P=0&h=180",
        "https://cdn.macrumors.com/article-new/2016/03/iPhone-SE-Front-Back.jpg?retina",
        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5789/5789725cv11d.jpg",
      ],
    },
    {
      id: 3,
      title: "Samsung Universe 9",
      description:
        "Samsung's new variant which goes beyond Galaxy to the Universe",
      price: 1249,
      discountPercentage: 15.46,
      rating: 4.09,
      stock: 36,
      brand: "Samsung",
      category: "smartphones",
      thumbnail: "https://tse3.mm.bing.net/th?id=OIP.UCNC8FNAlI-EetpW_xar0AHaDU&pid=Api&P=0&h=180",
      images: ["https://i5.walmartimages.com/asr/80aad70e-23d9-4bac-b938-2a64c5e7a563.2e769bfe8c5e1dc83053b6edb4d053ff.jpeg?odnWidth=1000&odnHeight=1000&odnBg=ffffff",
               "https://tse3.mm.bing.net/th?id=OIP.UCNC8FNAlI-EetpW_xar0AHaDU&pid=Api&P=0&h=180",
      ],
    },
    {
      id: 4,
      title: "OPPOF19",
      description: "OPPO F19 is officially announced on April 2021.",
      price: 280,
      discountPercentage: 17.91,
      rating: 4.3,
      stock: 123,
      brand: "OPPO",
      category: "smartphones",
      thumbnail: "https://www.chooseyourmobile.com/wp-content/uploads/2021/04/Oppo-F19-Colors.jpg",
      images: [
        "https://english.onlinekhabar.com/wp-content/uploads/2021/03/oppo-f.jpg",
        "https://data1.ibtimes.co.in/en/full/759880/oppo-f19-review.jpg",
        "https://tse4.mm.bing.net/th?id=OIP.SEXq0dnBVQJ2hS8M4Mt77wHaGQ&pid=Api&P=0&h=180",
        "https://tse2.mm.bing.net/th?id=OIP.AZJgqZT1y0BC62T9abA3JgHaEP&pid=Api&P=0&h=180",
        "https://www.chooseyourmobile.com/wp-content/uploads/2021/04/Oppo-F19-Colors.jpg",
      ],
    },
    {
      id: 5,
      title: "Huawei P30",
      description:
        "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
      price: 499,
      discountPercentage: 10.58,
      rating: 4.09,
      stock: 32,
      brand: "Huawei",
      category: "smartphones",
      thumbnail: "https://tse1.mm.bing.net/th?id=OIP.F7wrq7DJt2xsr_6cUPvCJgHaGj&pid=Api&P=0&h=180",
      images: [
        "https://tse1.mm.bing.net/th?id=OIP.F7wrq7DJt2xsr_6cUPvCJgHaGj&pid=Api&P=0&h=180",
        "https://cdn.shopify.com/s/files/1/2787/0602/products/p30_pro_all_colors_1200x1200.jpg?v=1580675601",
        "https://www.deepspecs.com/wp-content/uploads/2019/01/8-huawei-p30-deepspecs-com.jpg",
      ],
    },
  ];
  
  export { data };